# Generated by Django 3.0.8 on 2020-07-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbControlMoney', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='company',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='created_date',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='published_date',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='averageMonthPay',
            new_name='gastomensual',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
